import { TariffEntry } from "../types/tariff";
import { effectiveStatus } from "./../utils/effectiveStatus";

/**
 * Which currently-charged tariff a company's industry is exposed to.
 *
 * The stocks panel is titled "Likely Affected Stocks", but nothing connected
 * the list to the tariff data: three hardcoded maps in the component named 19
 * tickers, their sectors, and two pre-written sentences each. The sentence was
 * then chosen by the day's price direction, so the same company under the same
 * tariffs read "supply chain resilience" on a green day and "supply chain
 * disruptions" on a red one. The copy was generated by the ticker's own noise
 * and presented as tariff analysis.
 *
 * This replaces that with a join. A company's industry comes from the provider
 * (see StockQuote.industry), and this module answers what that industry is
 * actually being charged today, from the same CSV the tables read.
 */

/**
 * Statuses where a duty is actually being charged right now.
 *
 * An allowlist, not a list of terminal states to exclude. The first cut here
 * excluded Withdrawn/Ended/Suspended/Paused/Expired, mirroring the strike-
 * through rule in the tariff table, and a test caught that this let *Proposed*
 * through: a tariff announced for next year is not being collected, but it is
 * not terminal either, so a denylist counted it as exposure. Threatened and
 * Under Investigation fail the same way. Of the seven statuses in the
 * commodity data (Active, Proposed, Suspended, Under Investigation,
 * Threatened, Ended, Withdrawn) only one means money is changing hands.
 *
 * An allowlist is also the safer default for data written by a weekly agent:
 * a status nobody here has seen yet reads as "not charged" instead of silently
 * putting companies on the panel.
 */
const CHARGED_STATUSES = new Set(["Active", "Legacy Tariff", "Reciprocal Tariff", "Restricted"]);

/**
 * Industry to tariffed goods.
 *
 * Keyed on Finnhub's `finnhubIndustry`, which is what the profile call already
 * returns, and matched against the commodity names in tariffs_commodities.csv.
 *
 * This is the one curated artifact left, and it is deliberately the smallest
 * one: a dozen sector rules rather than a per-ticker script. It is also the
 * honest limit of the panel. Finnhub's taxonomy is coarse ("Technology" covers
 * Apple, HP and Corsair alike), so what this supports is a sector-level claim,
 * "this industry is under a 25% semiconductor tariff", and not a company-level
 * one about any particular firm's exposure. The UI wording has to match that.
 *
 * Patterns stay narrow on purpose. A blanket row like "All Imports" touches
 * every company on earth and would make the panel meaningless, so only goods
 * that name a sector are matched.
 */
export const INDUSTRY_GOODS: ReadonlyArray<{ industry: string; goods: RegExp }> = [
  { industry: "Metals & Mining", goods: /steel|aluminum|aluminium|copper|critical minerals|rare earth/i },
  { industry: "Semiconductors", goods: /semiconductor/i },
  { industry: "Technology", goods: /semiconductor|robotics/i },
  { industry: "Automobiles", goods: /automobile|motor vehicle|heavy-duty truck/i },
  { industry: "Machinery", goods: /heavy-duty truck|robotics|steel|aluminum/i },
  { industry: "Aerospace & Defense", goods: /steel|aluminum|aluminium/i },
  { industry: "Retail", goods: /chinese goods|small-value imports/i },
  { industry: "Pharmaceuticals", goods: /pharmaceutic/i },
  { industry: "Biotechnology", goods: /pharmaceutic/i },
  { industry: "Energy", goods: /solar panel|critical minerals/i },
  { industry: "Utilities", goods: /solar panel/i },
  { industry: "Logistics & Transportation", goods: /port fees|cargo handling|vessel/i },
  { industry: "Building", goods: /lumber|timber|upholstered furniture|steel|aluminum/i },
  { industry: "Furniture", goods: /upholstered furniture|lumber|timber/i },
];

export interface TariffExposure {
  /** The tariff line's own name, as the tables render it. */
  commodity: string;
  rate: number;
  rateDisplay: string;
  status: string;
  effectiveDate: string;
}

/**
 * The heaviest duty currently being charged on an industry's goods, or null.
 *
 * Highest rate wins because that is the exposure worth reporting; ties keep the
 * first match, which is CSV order. Returns null rather than a placeholder so a
 * caller can drop the company from the panel entirely: a stock with no live
 * tariff on its sector does not belong on a list of affected stocks, and that
 * is exactly the behaviour the old fixed list could not express.
 */
export function exposureFor(
  industry: string | null,
  tariffs: TariffEntry[],
  now: Date = new Date()
): TariffExposure | null {
  if (!industry) return null;

  const rules = INDUSTRY_GOODS.filter((rule) => rule.industry === industry);
  if (rules.length === 0) return null;

  let best: TariffExposure | null = null;

  for (const entry of tariffs) {
    if (entry.type !== "product") continue;
    if (!rules.some((rule) => rule.goods.test(entry.commodity))) continue;

    // Read the status as of today, not as of the last CSV refresh, so a tariff
    // whose start date has passed since the weekly run counts. Same rule the
    // tables apply, and it is what makes a Proposed row become chargeable on
    // the day it takes effect rather than at the next refresh.
    const status = effectiveStatus(entry.status, entry.effectiveDate, now);
    if (!CHARGED_STATUSES.has(status)) continue;

    // A negative rate is the sentinel for "Restricted"/"Banned"; a zero-rate
    // line is a real tariff line worth naming, so only the sentinel is skipped
    // for ranking purposes while still being eligible.
    if (best === null || entry.rate > best.rate) {
      best = {
        commodity: entry.commodity,
        rate: entry.rate,
        rateDisplay: entry.rateDisplay ?? `${entry.rate}%`,
        status,
        effectiveDate: entry.effectiveDate,
      };
    }
  }

  return best;
}

/**
 * Order companies so the panel leads with the heaviest duty without showing
 * the same sentence six times in a row.
 *
 * A plain sort by rate is the honest ranking but reads badly in a scrolling
 * marquee: Metals & Mining, Machinery and Aerospace & Defense are all charged
 * on Steel & Aluminum, so the first six cards were identical apart from the
 * ticker, which looks like a rendering fault rather than a finding.
 *
 * Sectors are still ranked by the duty they carry; this only takes one company
 * from each in turn, so the first screen shows the top sector, then the next,
 * and repeats. Nothing is hidden or reordered across rate boundaries in a way
 * that would misstate which exposure is largest.
 */
export function interleaveBySector<T extends { exposure: TariffExposure | null }>(
  quotes: T[]
): T[] {
  const bySector = new Map<string, T[]>();
  for (const quote of quotes) {
    if (!quote.exposure) continue;
    const key = quote.exposure.commodity;
    const group = bySector.get(key);
    if (group) group.push(quote);
    else bySector.set(key, [quote]);
  }

  // Heaviest-charged sector first; ties keep insertion order, which is the
  // caller's own ordering.
  const groups = [...bySector.values()].sort(
    (a, b) => (b[0].exposure?.rate ?? 0) - (a[0].exposure?.rate ?? 0)
  );

  const ordered: T[] = [];
  for (let round = 0; ordered.length < quotes.length; round++) {
    let placed = false;
    for (const group of groups) {
      if (round < group.length) {
        ordered.push(group[round]);
        placed = true;
      }
    }
    // Guard against a caller passing an entry with no exposure, which would
    // otherwise never be placed and spin this loop forever.
    if (!placed) break;
  }
  return ordered;
}
